### ISSUE TITLE
bug in overlap calculation in trax library (gives undesired results)

### ISSUE THREAD

**Issue by johnbeuving** [vicoslab/vot-toolkit#29]
When calculating the overlap between the polygons there is an error in calculating the height (or width).

In the function compute_polygon_overlap the boundaries are calculated as follows:
float x = MIN(b1.left, b2.left);
float y = MIN(b1.top, b2.top);

int width = (int) ((MAX(b1.right, b2.right)) - x);
int height = (int) ((MAX(b1.bottom, b2.bottom)) - y);

These calculations depend on the macros MAX and MIN defined in the file region.h (trax/lib/region.h)
However because of the missing brackets around MAX (and MIN) the results of the rasterisiation function is not always as desired.  This can be verified by printing the value of for example the calculated height.

The macro is currently defined as :
#define MAX(a,b) ((a) > (b)) ? (a) : (b)
but should be defined as:
#define MAX(a,b) (((a) > (b)) ? (a) : (b))

If required more details can be provided.

**Comment by lukacu** [comment]
Thanks for the report, I will look into it once I return from my vacation.

On Friday, February 6, 2015, johnbeuving <notifications@github.com> wrote:

> When calculating the overlap between the polygons there is an error in
> calculating the height (or width).
>
> In the function compute_polygon_overlap the boundaries are calculated as
> follows:
> float x = MIN(b1.left, b2.left);
> float y = MIN(b1.top, b2.top);
>
> int width = (int) ((MAX(b1.right, b2.right)) - x);
> int height = (int) ((MAX(b1.bottom, b2.bottom)) - y);
>
> These calculations depend on the macros MAX and MIN defined in the file
> region.h (trax/lib/region.h)
> However because of the missing brackets around MAX (and MIN) the results
> of the rasterisiation function is not always as desired. This can be
> verified by printing the value of for example the calculated height.
>
> The macro is currently defined as :
> #define MAX(a,b) ((a) > (b)) ? (a) : (b)
> but should be defined as:
> #define MAX(a,b) (((a) > (b)) ? (a) : (b))
>
> If required more details can be provided.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vicoslab/vot-toolkit/issues/29>.
>


-- 
Luka Čehovin
http://luka.tnode.com

**Comment by lukacu** [comment]
Fixed in lukacu/trax#3.
