### ISSUE TITLE
Where is initialize_defaults?

### ISSUE THREAD

**Issue by davisking** [vicoslab/vot-toolkit#32]
I downloaded a fresh copy of the repository, went into the root folder, ran octave and then typed the following:
octave:1> addpath(pwd)
octave:2> cd working_dir/
octave:3> vot_initialize 
error: 'initialize_defaults' undefined near line 9 column 1
error: called from:
error:   /home/davis/temp/new-vot-toolkit/vot_initialize.m at line 9, column 1

I get an error that it's trying to call initialize_defaults but it apparently isn't anywhere in the repository.

**Comment by lukacu** [comment]
Yes, I have removed the initialize_defaults a few commits ago, but forgot to check the initialization procedure, since my workspace is already initialized. I will commit a fix today.

**Comment by davisking** [comment]
Sweet, thanks.
