### ISSUE TITLE
region_noise experiment for vot2013 stack

### ISSUE THREAD

**Issue by vojirt** [vicoslab/vot-toolkit#37]
The initialization rectangle for the vot2013 region_noise
experiment is in 4 corners format, instead of top_left x y and width height
as it is for the baseline expetiment.
This is probably some kind of unintentional behaviour, since vot2013 should
use the old format as all the sequences are annotated with axis-align bboxes and the trackers, that are evaluated on that benchmark, expect the old format.

**Comment by lukacu** [comment]
Yes, this can be a problem with the old integration approach, TraX should convert regions on the fly. I will fix this.
