### ISSUE TITLE
create_trackers.m tries to read directory as a list file

### ISSUE THREAD

**Issue by lukacu** [vicoslab/vot-toolkit#44]
If the resutls folder is added to the matlab path the create_trackers function will fail because the check if a file with a specific name exists on the disk is too vague. The function should only check if a file exists relative to the active workspace.

**Comment by GustavHager** [comment]
I have fixed this and a related issue (wrong indexing on varargin), pull request once i can untangle it from my other fixes.

**Comment by lukacu** [comment]
I will close the ticket once I test that the fix really works.
