### ISSUE TITLE
mexfiles does not build correctly

### ISSUE THREAD

**Issue by GustavHager** [vicoslab/vot-toolkit#48]
It seems there is some failure with the include files / syntax error.

error message is:
ERROR: Unable to compile MEX function: "/home/gustav/Documents/MATLAB/vot/vot-toolkit/sequence/region_overlap.cpp:7:1: error: ‘region_container’ does not name a type
 region_container* get_polygon(const mxArray * input) {
 ^
/home/gustav/Documents/MATLAB/vot/vot-toolkit/sequence/region_overlap.cpp: In function ‘void mexFunction(int, mxArray**, int, const mxArray**)’:
/home/gustav/Documents/MATLAB/vot/vot-toolkit/sequence/region_overlap.cpp:45:2: error: ‘region_container’ was not declared in this scope
  region_container* p1;
  ^
/home/gustav/Documents/MATLAB/vot/vot-toolkit/sequence/region_overlap.cpp:45:20: error: ‘p1’ was not declared in this scope
  region_container* p1;
                    ^
/home/gustav/Documents/MATLAB/vot/vot-toolkit/sequence/region_overlap.cpp:46:20: error: ‘p2’ was not declared in this scope
  region_container* p2;
                    ^
/home/gustav/Documents/MATLAB/vot/vot-toolkit/sequence/region_overlap.cpp:60:26: error: ‘get_polygon’ was not declared in this scope
  p1 = get_polygon(prhs[0]);
                          ^
/home/gustav/Documents/MATLAB/vot/vot-toolkit/sequence/region_overlap.cpp:68:9: error: ‘region_overlap’ was not declared in this scope
         region_overlap overlap = region_compute_overlap(p1, p2);
         ^
/home/gustav/Documents/MATLAB/vot/vot-toolkit/sequence/region_overlap.cpp:68:24: error: expected ‘;’ before ‘overlap’
         region_overlap overlap = region_compute_overlap(p1, p2);
                        ^
/home/gustav/Documents/MATLAB/vot/vot-toolkit/sequence/region_overlap.cpp:70:21: error: ‘overlap’ was not declared in this scope
         result[0] = overlap.overlap;

**Comment by lukacu** [comment]
Yes, this is a problem if you are using dev version because of the ongoing work on #36. At the moment you also have to change the code in compile_all_native to use dev version of the trax library because we had to rename some structures.

**Comment by lukacu** [comment]
Anyway, this should not be an issue once we both dev versions to their corresponding master branches, so I am closing the report.
